name = "HealthDash"
uuid = "6f3ddfe2-4dd4-4bc9-a460-dc226a640b54"
authors = ["Kosuri Indu <kosurilindu@gmail.com>"]
version = "0.1.0"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
DBInterface = "2.6.1"
DataFrames = "1.8.1"
Dates = "1.6"
DuckDB = "1.4.1"
FunSQL = "0.15.0"
Genie = "5.33.15"
JSON3 = "1.14.3"
Stipple = "0.31"
StippleUI = "0.24.13"
Test = "1.6"
UUIDs = "1.11.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
